#!/bin/bash

ACTION=$1

if [[ $2 = '-d' ]]; then
  TAG='-debug'
else
  TAG=''
fi

case $ACTION in
build)
  echo build $TAG
  docker build -t homeski/macbot .
  ;;
run)
  echo run $TAG

  docker network create --driver bridge macbot_nw$TAG

  if [[ -z $TAG ]]; then
    # non-debug
    docker run -d -p 3001:8080 --name macbot   --network=macbot_nw       homeski/macbot
    docker run -d -p 8081:80   --name=influxdb --network=macbot_nw-debug homeski/grafana-influxdb
  else
    # debug
    docker run -d -p 3002:8080 --name macbot$TAG   --network=macbot_nw$TAG   homeski/macbot
    docker run -d -p 8082:80   --name=influxdb$TAG --network=macbot_nw$TAG   homeski/grafana-influxdb
  fi
  ;;
test)
  echo test $TAG
  if [[ -z $TAG ]]; then
    # non-debug
    curl -d '{"text":"macbot"}' -H "Content-Type: application/json" localhost:3001/groupme
  else
    # debug
    curl -d '{"text":"macbot"}' -H "Content-Type: application/json" localhost:3002/groupme
  fi
  ;;
kill)
  echo kill $TAG
  docker kill macbot$TAG
  docker rm macbot$TAG

  docker kill influxdb$TAG
  docker rm influxdb$TAG

  docker network rm macbot_nw$TAG
  ;;
watch)
  echo watch $TAG
  docker logs -f macbot$TAG
  ;;
*)
  echo 'unknown command. use build | run | test | kill | watch and -d for debug'
  ;;
esac
