- hosts: localhost
  name: Template configs
  vars:
    macbot:
      groupme_access_token: ''
      bots: []
      matches: {}
      listen: 127.0.0.1
      port: 3000
  tasks:
    - name: Template config/credentials.yml
      template:
        src: templates/credentials.yml.j2
        dest: config/credentials.yml

    - name: Template config/matches.yml
      template:
        src: templates/matches.yml.j2
        dest: config/matches.yml

    - name: Template docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: docker-compose.yml



- hosts: localhost
  connection: local
  name: docker-compose management
  tasks:
    - name: docker-compose stop
      docker_service:
        project_src: "."
        state: absent
      register: output

    - name: docker-compose start
      docker_service:
        project_src: "."
        state: present
        build: yes
        scale:
          web: 1
      register: output

  tags:
    - docker-compose
